name: Web & API Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  web-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Execute Web Test
        run: ./gradlew demoblaze -Ptags="@web"

      - name: Archive Web Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber-Web-Report
          path: reports/cucumber-web.html

  api-test:
    runs-on: ubuntu-latest
    needs: web-test  # Pastikan API Test menunggu Web Test selesai

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Execute API Test
        run: ./gradlew dummyapi -Ptags="@api"

      - name: Download Web Test Report
        uses: actions/download-artifact@v4
        with:
          name: Cucumber-Web-Report
          path: reports/

      - name: Buat index.html untuk gabungan laporan
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Test Reports</title>
              <style>
                  body { font-family: Arial, sans-serif; text-align: center; }
                  iframe { width: 90%; height: 500px; border: none; margin: 10px; }
              </style>
          </head>
          <body>
              <h1>Test Reports</h1>
              <h2>Cucumber Web Report</h2>
              <iframe src="cucumber-web.html"></iframe>
              <h2>Cucumber API Report</h2>
              <iframe src="cucumber-api.html"></iframe>
          </body>
          </html>' > reports/index.html

      - name: Pastikan reports ada
        run: |
          ls -la reports/

      - name: Archive Combined Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cucumber-Web-API-Report
          path: reports/

      - name: Deploy Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
