name: Web Automation Workflow

#Events
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    # VM
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4

    # Setup Java
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    # Install Browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2
          
    # Setup Gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # Execution gradlew command for runing cumcumber
    - name: Execute test
      run: ./gradlew demoblaze -Ptags="@web"


    # Archive test result
    - name: Archive test result
      uses: actions/upload-artifact@v4.5.0
      if: always()
      with:
        name: Cucumber Report
        path: reports

    # Rename cucumber-web.html to index-web.html
    - name: Rename cucumber-web.html to index-web.html
      run: mv reports/cucumber-web.html reports/index-web.html
    
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports
